yarn add \
arid \
babel-runtime \
bh-mj-detail \
bh-mj-issue \
bh-mj-prompt \
booleanize \
doubt \
filpos \
jquery \
mjml \
mjml-core \
mjml-section \
mjml-wrapper \
nbyx \
parseon \
react \
sxty4 \
wichevr \
--save && \
yarn add \
babel-cli \
babel-core \
babel-loader \
babel-plugin-transform-runtime \
babel-plugin-transform-decorators-legacy \
babel-plugin-transform-react-constant-elements \
babel-plugin-transform-react-inline-elements \
babel-preset-latest \
babel-preset-react \
bower-resolve-webpack-plugin \
css-loader \
electron \
gulp \
gulp-babel \
gulp-changed \
gulp-debug \
gulp-plumber \
gulp-rename \
gulp-replace \
gulp-sourcemaps \
looks-same \
mjml \
mocha \
nchunk \
plough \
postcss-loader \
resolve-url-loader \
sass-loader \
scrshot \
should \
source-map-loader \
style-loader \
url-loader \
wdio-json-reporter \
wdio-mocha-framework \
wdio-selenium-standalone-service \
webdriverio \
webpack \
webpack-bundle-analyzer \
webpack-dev-server \
yargs \
--dev && \
bower install \
arid \
bh-mj-detail \
bh-mj-issue \
bh-mj-prompt \
booleanize \
doubt \
filpos \
jquery \
nbyx \
parseon \
react \
sxty4 \
wichevr \
--force-latest \
--save
